#!/usr/bin/env bash
# Room suite one-click installer (macOS / Linux).
# Run from the unzipped suite directory (sibling of bin/).
set -euo pipefail

SUITE_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_SRC="$SUITE_DIR/bin"
SHARE="${ROOM_HOME:-$HOME/.local/share/room}"
BIN_LINK="${ROOM_BIN_DIR:-$HOME/.local/bin}"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/room-tui"

echo ""
echo "========================================"
echo "  Room - product installer"
echo "========================================"
echo ""

if [[ ! -x "$BIN_SRC/room" && ! -f "$BIN_SRC/room" ]]; then
  echo "X missing $BIN_SRC/room (is this the suite package?)" >&2
  exit 1
fi
if [[ ! -f "$BIN_SRC/paper-derived" ]]; then
  echo "X missing $BIN_SRC/paper-derived" >&2
  exit 1
fi

HAS_PI=0
if [[ -f "$BIN_SRC/pi" ]]; then
  HAS_PI=1
fi

echo "-> install root: $SHARE"
mkdir -p "$SHARE/bin" "$BIN_LINK" "$CFG_DIR"

# Copy entire bin/ (room, paper-derived, pi, theme/, assets/, ...)
# pi bun binary requires theme/dark.json next to the executable.
cp -R "$BIN_SRC/." "$SHARE/bin/"
chmod +x "$SHARE/bin/room" "$SHARE/bin/paper-derived" 2>/dev/null || true
chmod +x "$SHARE/bin/oob-divzero" 2>/dev/null || true
if [[ $HAS_PI -eq 1 ]]; then
  chmod +x "$SHARE/bin/pi" 2>/dev/null || true
fi

# Optional tools/ (LibreOffice, c-toolchain)
if [[ -d "$SUITE_DIR/tools" ]]; then
  echo "-> copying tools/ (doc converter / C toolchain)"
  mkdir -p "$SHARE/tools"
  cp -R "$SUITE_DIR/tools/." "$SHARE/tools/"
fi
if [[ -f "$SUITE_DIR/VERSION" ]]; then
  cp -f "$SUITE_DIR/VERSION" "$SHARE/VERSION"
fi

if [[ $HAS_PI -eq 1 && ! -f "$SHARE/bin/theme/dark.json" ]]; then
  echo "! pi present but theme/dark.json missing - LLM may fail until re-packed with assets" >&2
fi

# Prefer running from SHARE/bin so room finds sibling paper-derived / pi.
cat > "$BIN_LINK/room" <<EOF
#!/usr/bin/env bash
# Room product launcher (auto-generated)
export ROOM_INSTALL_BIN="$SHARE/bin"
# Prefer suite-bundled pi over random PATH entry
if [[ -x "$SHARE/bin/pi" ]]; then
  export PI_BIN="$SHARE/bin/pi"
fi
exec "$SHARE/bin/room" "\$@"
EOF
cat > "$BIN_LINK/paper-derived" <<EOF
#!/usr/bin/env bash
# paper-derived product launcher (auto-generated by Room suite)
exec "$SHARE/bin/paper-derived" "\$@"
EOF
chmod +x "$BIN_LINK/room" "$BIN_LINK/paper-derived"
if [[ -x "$SHARE/bin/oob-divzero" ]]; then
  cat > "$BIN_LINK/oob-divzero" <<EOF
#!/usr/bin/env bash
# oob-divzero product launcher (auto-generated by Room suite)
export ROOM_INSTALL_BIN="$SHARE/bin"
export ROOM_HOME="$SHARE"
if [[ -x "$SHARE/tools/c-toolchain/bin/clang" ]]; then
  export OOB_CC="$SHARE/tools/c-toolchain/bin/clang"
  export ROOM_CC="\$OOB_CC"
  export ROOM_C_TOOLCHAIN="$SHARE/tools/c-toolchain"
  export PATH="$SHARE/tools/c-toolchain/bin:\$PATH"
fi
exec "$SHARE/bin/oob-divzero" "\$@"
EOF
  chmod +x "$BIN_LINK/oob-divzero"
fi
if [[ $HAS_PI -eq 1 ]]; then
  cat > "$BIN_LINK/pi" <<EOF
#!/usr/bin/env bash
# pi product launcher (bundled with Room suite; cwd-independent)
exec "$SHARE/bin/pi" "\$@"
EOF
  chmod +x "$BIN_LINK/pi"
fi

# Config sample (do not overwrite user config)
if [[ ! -f "$CFG_DIR/config.toml" && -f "$SUITE_DIR/config.example.toml" ]]; then
  cp "$SUITE_DIR/config.example.toml" "$CFG_DIR/config.toml"
  echo "-> wrote $CFG_DIR/config.toml (from example; edit provider/model)"
fi

# Required skills (paper-derived docs; engine binary is suite bin/paper-derived)
install_suite_skills() {
  local src_root="$SUITE_DIR/skills"
  if [[ ! -d "$src_root" ]]; then
    echo "X suite has no skills/ - re-pack with packaging/skills (vendored paper-derived)" >&2
    exit 1
  fi
  # Room-branded agent dir (NOT system ~/.pi; matches piConfig.configDir)
  local room_pi_agent="${XDG_CONFIG_HOME:-$HOME/.config}/room-tui/agent"
  local room_pi_skills="$room_pi_agent/skills"
  local product_skills="$SHARE/skills"
  local bin_skills="$SHARE/bin/skills"
  local dest_roots=(
    "$room_pi_skills"
    "$product_skills"
    "$bin_skills"
  )
  mkdir -p "$room_pi_agent"
  if [[ ! -f "$room_pi_agent/settings.json" ]]; then
    echo '{}' >"$room_pi_agent/settings.json"
  fi
  local name src dst root n=0
  for src in "$src_root"/*; do
    [[ -d "$src" ]] || continue
    name="$(basename "$src")"
    [[ -f "$src/SKILL.md" ]] || continue
    for root in "${dest_roots[@]}"; do
      mkdir -p "$root"
      dst="$root/$name"
      rm -rf "$dst"
      mkdir -p "$dst"
      cp -R "$src/." "$dst/"
      # no nested capability binaries
      rm -f "$dst/paper-derived" "$dst/paper-derived.exe" 2>/dev/null || true
      rm -f "$dst/oob-divzero" "$dst/oob-divzero.exe" 2>/dev/null || true
      rm -rf "$dst/pkg" 2>/dev/null || true
      if [[ ! -f "$dst/SKILL.md" ]]; then
        echo "X skill copy failed: $dst" >&2
        exit 1
      fi
    done
    n=$((n + 1))
    echo "OK skill $name"
    echo "    -> $room_pi_skills/$name  (Room pi-agent, isolated)"
    echo "    -> $product_skills/$name"
  done
  if [[ $n -lt 1 ]]; then
    echo "X no skills installed from suite/skills" >&2
    exit 1
  fi
  for req in paper-derived oob-divzero; do
    if [[ ! -f "$room_pi_skills/$req/SKILL.md" && ! -f "$product_skills/$req/SKILL.md" ]]; then
      echo "X required skill missing after install: $req" >&2
      exit 1
    fi
  done
  # Room-branded pi: ROOM_CODING_AGENT_DIR (default ~/.config/room-tui/agent)
  export ROOM_INSTALL_BIN="$SHARE/bin"
  export ROOM_HOME="$SHARE"
  export ROOM_CODING_AGENT_DIR="$room_pi_agent"
  export ROOM_PI_AGENT_DIR="$room_pi_agent"
  export PI_CODING_AGENT_DIR="$room_pi_agent"
  if [[ -x "$SHARE/tools/c-toolchain/bin/clang" ]]; then
    export OOB_CC="$SHARE/tools/c-toolchain/bin/clang"
    export ROOM_CC="$OOB_CC"
    export ROOM_C_TOOLCHAIN="$SHARE/tools/c-toolchain"
  fi
  {
    echo "export ROOM_INSTALL_BIN=\"$SHARE/bin\""
    echo "export ROOM_HOME=\"$SHARE\""
    echo "export ROOM_CODING_AGENT_DIR=\"$room_pi_agent\""
    echo "export ROOM_PI_AGENT_DIR=\"$room_pi_agent\""
    echo "export PI_CODING_AGENT_DIR=\"$room_pi_agent\""
    if [[ -x "$SHARE/tools/c-toolchain/bin/clang" ]]; then
      echo "export OOB_CC=\"$SHARE/tools/c-toolchain/bin/clang\""
      echo "export ROOM_CC=\"$SHARE/tools/c-toolchain/bin/clang\""
      echo "export ROOM_C_TOOLCHAIN=\"$SHARE/tools/c-toolchain\""
      echo "export PATH=\"$SHARE/tools/c-toolchain/bin:\$PATH\""
    fi
  } >"${XDG_CONFIG_HOME:-$HOME/.config}/room-tui/env.sh" 2>/dev/null || true
  echo "OK Room agent dir -> $room_pi_agent  (!= system ~/.pi)"
  echo "OK ROOM_CODING_AGENT_DIR -> $room_pi_agent"
}
echo "-> installing required skills"
install_suite_skills

echo "OK room           -> $BIN_LINK/room"
echo "OK paper-derived  -> $BIN_LINK/paper-derived"
if [[ -x "$BIN_LINK/oob-divzero" || -x "$SHARE/bin/oob-divzero" ]]; then
  echo "OK oob-divzero    -> ${BIN_LINK}/oob-divzero"
else
  echo "! oob-divzero    not in suite - re-pack with --oob-divzero"
fi
if [[ -x "$SHARE/tools/c-toolchain/bin/clang" || -x "$SHARE/tools/c-toolchain/bin/gcc" ]]; then
  echo "OK c-toolchain    -> $SHARE/tools/c-toolchain (oob ASan)"
else
  echo "! c-toolchain    missing - oob ASan needs clang (fetch-c-toolchain + re-pack)"
fi
if [[ $HAS_PI -eq 1 ]]; then
  echo "OK pi             -> $BIN_LINK/pi  (bundled)"
  if [[ -f "$SHARE/bin/theme/dark.json" ]]; then
    echo "OK pi theme       -> $SHARE/bin/theme/"
  fi
else
  echo "! pi             not in suite - install pi separately for LLM"
fi
echo "OK binaries       -> $SHARE/bin/"
echo ""

# PATH check
if ! command -v room >/dev/null 2>&1; then
  echo "Add to PATH (zsh/bash):"
  echo "  export PATH=\"$BIN_LINK:\$PATH\""
  echo "Then:  source ~/.zshrc   # or open a new terminal"
  echo ""
else
  echo "room on PATH -> $(command -v room)"
fi

if [[ $HAS_PI -eq 1 ]]; then
  echo "pi bundled     -> $SHARE/bin/pi"
elif command -v pi >/dev/null 2>&1; then
  echo "pi on PATH     -> $(command -v pi)"
else
  echo ""
  echo "!  pi not found"
  echo "   Room needs pi for LLM. Re-pack suite with --pi, or install pi on PATH."
  echo ""
fi

# Hard seed via room binary (embedded skills fallback)
ROOM_BIN_REAL="$SHARE/bin/room"
if [[ -x "$ROOM_BIN_REAL" ]]; then
  export ROOM_INSTALL_BIN="$SHARE/bin"
  export ROOM_CODING_AGENT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/room-tui/agent"
  echo "-> room skills-seed"
  if ! "$ROOM_BIN_REAL" skills-seed; then
    echo "X room skills-seed failed - required skills (paper-derived, oob-divzero) not installed" >&2
    exit 1
  fi
fi

echo "Next:"
echo "  room --version"
echo "  room doctor"
echo "  cd /path/to/your-project && room"
echo ""

# Best-effort doctor if room is invokable
if [[ -x "$BIN_LINK/room" ]]; then
  export PATH="$BIN_LINK:$PATH"
  export ROOM_INSTALL_BIN="$SHARE/bin"
  if [[ -x "$SHARE/bin/pi" ]]; then
    export PI_BIN="$SHARE/bin/pi"
  fi
  if "$BIN_LINK/room" --version >/dev/null 2>&1; then
    echo "-- room doctor (preview) --"
    "$BIN_LINK/room" doctor || true
  fi
fi
