#!/usr/bin/env bash
# DEV-ONLY install: editable venv + ~/.local/bin/room shim.
# Product users should NOT use this - take a room-suite zip and run install.sh
# (see installs/README.md and PACKAGING.md).
#
# Usage:
#   ./scripts/install-global.sh          # create/reuse venv, install shim
#   ./scripts/install-global.sh --force  # recreate venv after path moves
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENV="$ROOT/.venv"
BIN_DIR="${ROOM_BIN_DIR:-$HOME/.local/bin}"
TARGET="$BIN_DIR/room"
FORCE=0
[[ "${1:-}" == "--force" || "${1:-}" == "-f" ]] && FORCE=1

need_venv=0
if [[ $FORCE -eq 1 ]]; then
  need_venv=1
elif [[ ! -x "$VENV/bin/python3" || ! -x "$VENV/bin/room" ]]; then
  need_venv=1
else
  # Detect broken shebang after directory rename (bad interpreter).
  if ! "$VENV/bin/python3" -c "import room_tui" 2>/dev/null; then
    echo "-> venv looks broken (import failed); recreating..."
    need_venv=1
  fi
fi

if [[ $need_venv -eq 1 ]]; then
  echo "-> creating venv + installing package..."
  rm -rf "$VENV"
  if command -v uv >/dev/null 2>&1; then
    (cd "$ROOT" && uv venv .venv && uv pip install -e ".[dev]")
  else
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install -e "$ROOT[dev]"
  fi
fi

mkdir -p "$BIN_DIR"
cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# Auto-generated by room-tui/scripts/install-global.sh
exec "$VENV/bin/room" "\$@"
EOF
chmod +x "$TARGET"

# remove old pd-tui shim if present
if [[ -f "$BIN_DIR/pd-tui" ]]; then
  rm -f "$BIN_DIR/pd-tui"
  echo "OK removed legacy: $BIN_DIR/pd-tui"
fi

echo "OK installed: $TARGET"
echo
if ! command -v room >/dev/null 2>&1; then
  echo "Add to PATH (zsh):"
  echo "  export PATH=\"$BIN_DIR:\$PATH\""
  echo "Then:  source ~/.zshrc"
else
  echo "room is on PATH -> $(command -v room)"
fi
echo
echo "Usage (like pi / claude / grok):"
echo "  cd /path/to/your-project"
echo "  room"
echo "  room -s sess_xxx"
echo "  room doctor"
echo
echo "If the project directory was renamed:  ./scripts/install-global.sh --force"
